name: Basic CI setup (installation, style checks, tests)
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.x']
    name: Python ${{ matrix.python-version }} pipeline
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package and dev dependencies
        run: |
          pip install '.[dev]'
      - name: Check style of package
        run: pre-commit run --all
      - name: Run tests
        run: pytest --junit-xml=junit-reports/test_results.xml tests
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results (Python ${{ matrix.python-version }})
          path: junit-reports/test_results.xml
      - name: Check 'fret-to-robot' command transforms without errors
        run: |
          cd examples/digital_microscope/assets/
          fret-to-robot req_fret.json
